import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { Toast } from '@/components/ui/toast';
import { Toaster } from '@/components/ui/toaster';
import DesignerContextProvider from '@/context/DesignerContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Formz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body className={inter.className}>
      <DesignerContextProvider>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem  
            disableTransitionOnChange
          >
        {children}
        <Toaster/>
        </ThemeProvider>
        </DesignerContextProvider>
        </body>
    </html>
    </ClerkProvider>

  );
}
